export const ADD_POST = 'ADD_POST';
export const GET_POST = 'GET_POST';
export const GET_POSTS = 'GET_POSTS';
export const HANDLE_SORTING = 'HANDLE_SORTING';
export const EDITING_POST = 'EDITING_POST';
export const EDIT_POST = 'EDIT_POST';
export const REMOVE_POST = 'REMOVE_POST';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_POSTS_FROM_CATEGORIES = 'GET_POSTS_FROM_CATEGORIES';

export const ADD_COMMENT = 'ADD_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const EDITING_COMMENT = 'EDITING_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const GET_COMMENTS = 'GET_COMMENTS';

export const UPDATE_SORTING = 'UPDATE_SORTING';